/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTaskPanel: typeof import('./components/TaskPanel/AddTaskPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskPanel: typeof import('./components/TaskPanel/TaskPanel.vue')['default']
    TimerPanel: typeof import('./components/TimerPanel/TimerPanel.vue')['default']
  }
}
